### ISSUE TITLE
Copyright infringement.

### ISSUE THREAD

**Issue by ProjectInfinity** [JulesBasanez/Exposed#1]
Please remove all infringing code, signs of infringement impending and future plans of infringement as seen here:
https://github.com/JulesBasanez/Exposed/commit/98e1231bb44d5f5eb8958090507344ff3571cbf3

This also invalidates your license at:
https://github.com/JulesBasanez/Exposed/blob/master/LICENSE

Our projects are not open source and you are not free to distribute any of the code as your own. Failure to comply will result in a DMCA takedown.

You have 48 hours, thank you.

**Comment by JulesBasanez** [comment]
I have done what you asked
